title: Copying Files on a Raspberry Pi
hero_image: images/banner.png
description: How to copy files in Raspbian
original_url: 
theme: cc-prototype
duration: 1 
listed: false
ingredient: true
interests: ""
technologies: ""
steps:
  - title: Copying Files on a Raspberry Pi
