title: rpi-copying-files
hero_image: images/banner.png
subtitle: rpi-copying-files subtitle
description: rpi-copying-files description
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: cc-prototype
published: false
steps:
  - title: Step one
    duration: 60
