---
title: Αντιγραφή αρχείων στο Raspberry Pi
hero_image: images/banner.png
description: Δύο τρόποι για την αντιγραφή αρχείων στο Raspbian
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - title: Αντιγραφή αρχείων στο Raspberry Pi
